# Read-only permissions and roles for weave-scope
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1alpha1
metadata:
  name: weave-cortex-mgr
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["get", "list", "watch"]
- nonResourceURLs: ["*"]
  verbs: ["*"]
---
# Grant permissions to weave-scope in the kube-system namespace.
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1alpha1
metadata:
  name: weave-cortex-mgr-role-binding
subjects:
- kind: ServiceAccount
  name: weave-cortex
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: weave-cortex-mgr
  apiGroup: rbac.authorization.k8s.io
