#If you are not logged into the US-South https://api.ng.bluemix.net region, change the image registry location to match your region.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ibmliberty-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ibmliberty
  template:
    metadata:
      labels:
        app: ibmliberty
    spec:
      containers:
      - name: ibmliberty
        image: registry.bluemix.net/ibmliberty
