# This policy allows outgoing network traffic from worker
# nodes to other IBM Cloud services. The example nets in this
# policy are for IBM Cloud Container Registry and IBM Cloud
# Monitoring with Sysdig.

apiVersion: projectcalico.org/v3
kind: GlobalNetworkPolicy
metadata:
  name: allow-public-services
spec:
  egress:
  - action: Allow
    destination:
      nets:
      # IBM Cloud Container Registry: Global registry
      - 169.60.72.144/28
      - 169.60.98.80/29
      - 169.61.76.176/28
      - 169.62.37.240/29
      - 169.63.104.232/29
      # IBM Cloud Container Registry: UK South nets for your own registry
      - 159.122.242.78/32
      - 159.122.224.242/32
      - 158.175.65.170/32
      - 158.175.111.42/32
      - 158.176.94.26/32
      - 158.176.95.146/32
      ports:
      - 443
      - 4443
    protocol: TCP
    source: {}
  - action: Allow
    destination:
      nets:
      # IBM Cloud Monitoring with Sysdig: UK South nets
      - 158.175.98.206/32
      - 141.125.73.118/32
      - 159.122.210.174/32
      ports:
      - 443
      - 6443
    protocol: TCP
    source: {}
  order: 1800
  selector: ibm.role == 'worker_public'
  types:
  - Egress
