# This policy allows outgoing network traffic from worker nodes in each zone
# of your cluster to the cluster master through the private service endpoint.
# Note that you must allow outgoing traffic for all of the zones within the region.

apiVersion: projectcalico.org/v3
kind: GlobalNetworkPolicy
metadata:
  name: allow-private-service-endpoint
spec:
  egress:
  - action: Allow
    destination:
      nets:
      # Nets for UK South: lon02, lon04, lon05, lon06
      - 166.9.34.5/32
      - 166.9.34.6/32
      - 166.9.36.10/32
      - 166.9.36.11/32
      - 166.9.36.12/32
      - 166.9.36.13/32
      - 166.9.38.6/32
      - 166.9.38.7/32
      ports:
      - 20000:32767
      - 443
    protocol: UDP
    source: {}
  - action: Allow
    destination:
      nets:
      # Nets for UK South: lon02, lon04, lon05, lon06
      - 166.9.34.5/32
      - 166.9.34.6/32
      - 166.9.36.10/32
      - 166.9.36.11/32
      - 166.9.36.12/32
      - 166.9.36.13/32
      - 166.9.38.6/32
      - 166.9.38.7/32
      ports:
      - 20000:32767
      - 443
    protocol: TCP
    source: {}
  order: 1900
  selector: ibm.role == 'worker_private'
  types:
  - Egress
