# This policy allows outgoing network traffic from worker nodes in each zone of
# your cluster to the cluster master through the public service endpoint. Note
# that you must allow outgoing traffic for all of the zones within the region.

apiVersion: projectcalico.org/v3
kind: GlobalNetworkPolicy
metadata:
  name: allow-public-service-endpoint
spec:
  egress:
  - action: Allow
    destination:
      nets:
      # Nets for AP North: che01, hkg02, seo01, sng01, tok02, tok04, tok05
      - 128.168.71.117/32
      - 161.202.126.210/32
      - 161.202.186.226/32
      - 165.192.69.69/32
      - 169.38.70.10/32
      - 169.56.69.242/32
      - 169.56.132.234/32
      ports:
      - 20000:32767
      - 443
    protocol: UDP
    source: {}
  - action: Allow
    destination:
      nets:
      # Nets for AP North: che01, hkg02, seo01, sng01, tok02, tok04, tok05
      - 128.168.71.117/32
      - 161.202.126.210/32
      - 161.202.186.226/32
      - 165.192.69.69/32
      - 169.38.70.10/32
      - 169.56.69.242/32
      - 169.56.132.234/32
      ports:
      - 20000:32767
      - 443
    protocol: TCP
    source: {}
  order: 1500
  selector: ibm.role == 'worker_public'
  types:
  - Egress
