apiVersion: v1
kind: Service
metadata:
  annotations:
    service.kubernetes.io/ibm-load-balancer-cloud-provider-enable-features: "ipvs"
  labels:
    app: echoserver-deployment
  name: iks-new-loadbalancer
  namespace: default
spec:
  ports:
  - name: port-1
    port: 1884
    protocol: TCP
    targetPort: 8080
  selector:
    app: echoserver-deployment
  type: LoadBalancer
  externalTrafficPolicy: Local    #  Preserve the original IP address of the client connecting
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echoserver-deployment
  namespace: default
  labels:
    app: echoserver-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: echoserver-deployment
  template:
    metadata:
      labels:
        app: echoserver-deployment
    spec:
      affinity:
        podAntiAffinity:      #  Spread out the "echoserver-deployment" pods on the worker nodes as evenly as possible
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - echoserver-deployment    # if a pod matching app=echoserver-deployment already runs on a node, try to find another node
              topologyKey: kubernetes.io/hostname
      containers:
        - name: echoserver
          image: k8s.gcr.io/echoserver:1.10
          env:
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
      restartPolicy: Always
