kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2beta1
metadata:
  name: elb-http-requests-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: httpd-frontend
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: External
    external:
      metricName: elb-http-requests
      targetValue: 10

