# This policy allows outgoing network traffic from worker nodes in each zone of
# your cluster to the cluster master through the public service endpoint. Note
# that you must allow outgoing traffic for all of the zones within the region.

apiVersion: projectcalico.org/v3
kind: GlobalNetworkPolicy
metadata:
  name: allow-public-service-endpoint
spec:
  egress:
  - action: Allow
    destination:
      nets:
      # Nets for US East: mon01, tor01, wdc04, wdc06, wdc07
      - 169.53.167.50/32
      - 169.54.126.219/32
      - 169.60.73.142/32
      - 169.60.101.42/32
      - 169.61.83.62/32
      - 169.61.109.34/32
      - 169.63.88.178/32
      - 169.63.88.186/32
      ports:
      - 20000:32767
      - 443
    protocol: UDP
    source: {}
  - action: Allow
    destination:
      nets:
      # Nets for US East: mon01, tor01, wdc04, wdc06, wdc07
      - 169.53.167.50/32
      - 169.54.126.219/32
      - 169.60.73.142/32
      - 169.60.101.42/32
      - 169.61.83.62/32
      - 169.61.109.34/32
      - 169.63.88.178/32
      - 169.63.88.186/32
      ports:
      - 20000:32767
      - 443
    protocol: TCP
    source: {}
  order: 1500
  selector: ibm.role == 'worker_public'
  types:
  - Egress
