# This policy allows outgoing network traffic from worker nodes in each zone of
# your cluster to the cluster master through the public service endpoint. Note
# that you must allow outgoing traffic for all of the zones within the region.

apiVersion: projectcalico.org/v3
kind: GlobalNetworkPolicy
metadata:
  name: allow-public-service-endpoint
spec:
  egress:
  - action: Allow
    destination:
      nets:
      # Nets for EU Central: ams03, mil01, osl01, par01, fra02, fra04, fra05
      - 149.81.78.114/32
      - 159.8.86.149/32
      - 159.122.141.69/32
      - 161.156.65.42/32
      - 169.50.56.174/32
      - 169.50.169.110/32
      - 169.51.73.50/32
      ports:
      - 20000:32767
      - 443
    protocol: UDP
    source: {}
  - action: Allow
    destination:
      nets:
      # Nets for EU Central: ams03, mil01, osl01, par01, fra02, fra04, fra05
      - 149.81.78.114/32
      - 159.8.86.149/32
      - 159.122.141.69/32
      - 161.156.65.42/32
      - 169.50.56.174/32
      - 169.50.169.110/32
      - 169.51.73.50/32
      ports:
      - 20000:32767
      - 443
    protocol: TCP
    source: {}
  order: 1500
  selector: ibm.role == 'worker_public'
  types:
  - Egress
